### ISSUE TITLE
Reddit comments not showing at all on Safari 8.0.5

### ISSUE THREAD

**Issue by alexh2** [xlexi/alientube#120]
After the latest OS X update, even though there was no update to Safari, Alientube has stopped working. That's it. That's the issue. I've tried deleting the plugin and re-adding it but that didn't work either. Don't know what else I could do.

**Comment by wigsternm** [comment]
I have the same problem.

**Comment by xlexi** [comment]
This is a known problem, it will be fixed when I have finished porting AlienTube 2 to Safari (alientube/issues/93) it is a slow process because I'm in my university exam period and Safari's extension system is awful to work with, but I will try to get it done this weekend. Sorry for the inconvenience

**Comment by Fofer** [comment]
Thanks - looking forward to the update - I am having the same issue here.  

Good luck with exams!

**Comment by PixelArray** [comment]
I'm also on Safari 8.0.5 and I've discovered that clicking the "Share your thoughts" button to make a YouTube comment makes the extension show and load the reddit comments.

**Comment by xlexi** [comment]
I am closing this as a duplicate, please pay attention to the following thread for now: https://github.com/xlexi/alientube/issues/93   
I am nearly done, I'm just having some problems with the new preferences page.
