### ISSUE TITLE
Please let us donate so you can afford the $99 fee for Safari extensions!

### ISSUE THREAD

**Issue by ywecur** [xlexi/alientube#146]
I know that I am not alone in wanting to use Safari for the battery life improvements. I would personally be glad to donate to you so you can afford the fee!

**Comment by xlexi** [comment]
Hello, I have agreed to revive the Safari version using the account of a project I am affiliated with. (see https://github.com/xlexi/alientube/issues/93#issuecomment-110882173)  I have no ETA on the release of the new version, I am currently taking a two week break from all work, so I will start working on it next Thursday.

I used to have a PayPal donation thing for AlienTube but I have closed it because I do not agree with PayPal's business practices and was unable to find a suitable alternative service. But thank you for the offer.
