### ISSUE TITLE
Firefox support discontinued?

### ISSUE THREAD

**Issue by Choonce** [xlexi/alientube#163]
I noticed that Alientube was taken off of AMO, is it coming back?

**Comment by HmmmQuestionMark** [comment]
It appears @xlexi is upset about the latest Firefox update: https://twitter.com/alexsorlie/status/661733981516398592

**Comment by xlexi** [comment]
Not until Mozilla reconsiders their position.

**Comment by The0x539** [comment]
Despite the functionality being far more comparable to the likes of Disconnect than to ad blockers?

**Comment by fireattack** [comment]
First of all I highly respect any decision you make/made. Thanks for developing this great addon.

But I have the same question as @The0x539 , by "builtin adblocker" do you mean "track protection"? If I read it correctly, isn't it only enabled in private mode *and* it's not essentially a ad blocker (it does blocks some AD we'd admit)?

**Comment by xlexi** [comment]
It blocks ads, I tested it. I'm not interested in the excuse for it they use to help themselves sleep at night.   
   
The Firefox version is a colossal pain in the arse to maintain due to a terrible addon system and nonsensical guidelines, Firefox share of my user basei is approximetely 4.7%.   
   
Due to personal problems I have very limited time to work on AlienTube these days and I have made the decission not to spend what time I have supporting those who directly attack part of my income, and the main livelyhood of many of my friends.

**Comment by fireattack** [comment]
That's reasonable I'd say. Just another great add-on left Firefox, nothing new :(

Thank you again!

**Comment by xlexi** [comment]
Sorry to disappoint you.

The extension is open source and anyone complying with the license are free to release it to Firefox. I don't blame to remove Firefox specific integration, but I will not make any effort to keep compatibility either.   
   
I see AlienTube has been forked on GitHub twice just today, they might be working on something.

**Comment by CreamyCookie** [comment]
@xlexi What's the problem with blocking ads? Most users probably already block ads, and if they don't, it would only affect you in private mode. What's more important, everybody's privacy, security & time OR content creators like you getting a few dollars more?

Anyway, thanks for the add-on! :+1:
