### ISSUE TITLE
Link the "number of comments" to the reddit thread

### ISSUE THREAD

**Issue by derimagia** [xlexi/alientube#171]
The number of comments are displayed, but it is currently not a link. I have a habit of clicking on this to view the comments and I often try to open it in a new window in Alientube. 

I know the title works, but I would say it should match how reddit is done when it can.

https://github.com/xlexi/alientube/blob/5b5d9e244d9461fa86490c8d57390a2dd6498e8f/TypeScript/CommentThread.ts#L105

**Comment by vincchan** [comment]
Sorry, could you point out where it displays the number of comments? I don't see it.

<img width="876" alt="screen shot 2016-02-01 at 00 34 46" src="https://cloud.githubusercontent.com/assets/868272/12706005/b9bbfad2-c87b-11e5-8890-228b958d3bb1.png">

**Comment by Derimagia** [comment]
Make sure you login to reddit and are using the latest version. See screenshot.

![comments](https://cloud.githubusercontent.com/assets/999489/12706042/4491f8dc-c84a-11e5-8017-8bfb5cf99664.png)

**Comment by Derimagia** [comment]
I just confirmed that the number of comments disappears when you are logged out. I'm not sure of rhe reasoning, and think it should be enabled if possible.

**Comment by Derimagia** [comment]
I took a look at the code and it looks like the reason it doesn't display for a non-logged in user is because it's being used as a "reply" button.

I propose the following actions then so we can make it similar to reddit:

1. Change the button so it is just a link to the thread.
2. Create a new button just called "reply" for replying and put it on the far right, similar to reddit.

If no one takes a crack at this I'll try to look at it when I get a chance later in the week.
