### ISSUE TITLE
Not compatible

### ISSUE THREAD

**Issue by Titanicoso** [xlexi/alientube#95]
My browser is basically chrome but different and the version is 36 instead of 37 and I can not download it. Could I download an old version or the real one but via a different website?

**Comment by xlexi** [comment]
The current version is not compatible because it isn't. Versions below the minimum current requirement lack features and frameworks that alientube is using. The last compatible version for Chrome 36 is available here: http://sc.alex.systems/b6a8-8fce71e601d4.crx  
  
Here is how to install it: http://lifehacker.com/install-chrome-extensions-from-outside-the-store-with-d-1596918011  

This version is deprecated and will have bugs, don't come to me with them.
